### ISSUE TITLE
First endpoints

### ISSUE THREAD

**Issue by olvap** [noili/my_todo#2]

**Comment by olvap** [comment]
Describe basic and firsts enpoints.

**Comment by noili** [comment]
## task

#create:
POST
url: /tasks
body:
~~~json
{"title": "create endpoints"}
~~~

#read all:
GET
url: /tasks

#read one:
GET
url: /tasks/:id

#update:
PUT
url: /tasks/:id
~~~json
{"title": "define endpoints"}
~~~

#delete:
DELETE
url: /tasks/:id

#change status to a resource:
PUT
url: /tasks/:id/done
